version: '3.8'

services:
  gitlab:
    image: docker.arvancloud.ir/gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_URL}'
        gitlab_rails['initial_root_password'] = '${GITLAB_ROOT_PASSWORD}'
    ports:
      - '8080:80'
      - '8443:443'
      - '2222:22'
    volumes:
      - /etc/gitlab/config:/etc/gitlab
      - /etc/gitlab/logs:/var/log/gitlab
      - /etc/gitlab/data:/var/opt/gitlab

  gitlab-runner:
    image: docker.arvancloud.ir/gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/gitlab/runner/config:/etc/gitlab-runner
